title: IRIS Community
description: IRIS Internal Site
author: SH Jin
logo: /jins00.github.io/static/img/mobigen_logo_small.png
github: https://github.com/jins00.github.io
about: Freelance developer

baseurl: ""
url: ""

allowsearch: true

disqus_shortname: IRIS
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
